spring:
  application:
    name: employee-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
